FROM ghcr.io/mlflow/mlflow:v2.14.1

RUN pip install --no-cache-dir psycopg2-binary boto3

EXPOSE 5000

CMD mlflow server \
  --host 0.0.0.0 \
  --port 5000 \
  --backend-store-uri "${MLFLOW_BACKEND_STORE_URI}" \
  --default-artifact-root "${MLFLOW_DEFAULT_ARTIFACT_ROOT}" \
  --serve-artifacts
