# Keycloak UBI micro has no package manager; healthcheck uses bash /dev/tcp.
FROM quay.io/keycloak/keycloak:24.0

USER root
COPY infra/docker/keycloak-healthcheck.sh /opt/keycloak-healthcheck.sh
RUN chmod +x /opt/keycloak-healthcheck.sh
USER 1000
